# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: customer.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pb2
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection

# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
    name='customer.proto',
    package='demo',
    serialized_pb='\n\x0e\x63ustomer.proto\x12\x04\x64\x65mo\";\n\x08\x43ustomer\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x11\n\tfirstName\x18\x02 \x02(\t\x12\x10\n\x08lastName\x18\x03 \x02(\t\"-\n\tCustomers\x12 \n\x08\x63ustomer\x18\x01 \x03(\x0b\x32\x0e.demo.CustomerB\x16\n\x04\x64\x65moB\x0e\x43ustomerProtos')

_CUSTOMER = _descriptor.Descriptor(
    name='Customer',
    full_name='demo.Customer',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='id', full_name='demo.Customer.id', index=0,
            number=1, type=3, cpp_type=2, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='firstName', full_name='demo.Customer.firstName', index=1,
            number=2, type=9, cpp_type=9, label=2,
            has_default_value=False, default_value=unicode("", "utf-8"),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='lastName', full_name='demo.Customer.lastName', index=2,
            number=3, type=9, cpp_type=9, label=2,
            has_default_value=False, default_value=unicode("", "utf-8"),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    extension_ranges=[],
    serialized_start=24,
    serialized_end=83,
)

_CUSTOMERS = _descriptor.Descriptor(
    name='Customers',
    full_name='demo.Customers',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='customer', full_name='demo.Customers.customer', index=0,
            number=1, type=11, cpp_type=10, label=3,
            has_default_value=False, default_value=[],
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    extension_ranges=[],
    serialized_start=85,
    serialized_end=130,
)

_CUSTOMERS.fields_by_name['customer'].message_type = _CUSTOMER
DESCRIPTOR.message_types_by_name['Customer'] = _CUSTOMER
DESCRIPTOR.message_types_by_name['Customers'] = _CUSTOMERS


class Customer(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _CUSTOMER

    # @@protoc_insertion_point(class_scope:demo.Customer)


class Customers(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _CUSTOMERS

    # @@protoc_insertion_point(class_scope:demo.Customers)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(),
                                                '\n\004demoB\016CustomerProtos')
# @@protoc_insertion_point(module_scope)
