#!/usr/bin/env ruby
# Generated by the protocol buffer compiler. DO NOT EDIT!

require 'protocol_buffers'

module Demo
  # forward declarations
  class Customer < ::ProtocolBuffers::Message; end
  class Customers < ::ProtocolBuffers::Message; end

  class Customer < ::ProtocolBuffers::Message
    set_fully_qualified_name "demo.Customer"

    optional :int64, :id, 1
    required :string, :firstName, 2
    required :string, :lastName, 3
  end

  class Customers < ::ProtocolBuffers::Message
    set_fully_qualified_name "demo.Customers"

    repeated ::Demo::Customer, :customer, 1
  end

end
